// GÉNÉRÉ depuis des captures RÉELLES du terminal (pyte), le 2026-09-23 sur un Mac série M,
// Qwen 3 4B (Dawn natif), cache chaud. Ne pas éditer à la main : un écran inventé afficherait
// des chiffres jamais mesurés (règle 4 du dépôt). Régénérer en refaisant les captures.
export type Seg = [string] | [string, string];
export type Capture = Seg[][];
export const SESSION: Capture = [[["kern ›", "boldRed"], [" give me 3 advantages of TypeScript as a list with bold titles, and one short code example"]], [["Type Safety", "bold"], [": Ensures that variables are used correctly by the compiler, reducing runtime errors."]], [], [["Better Tooling", "bold"], [": Provides features like intellisense, refactoring support, and error detection during development."]], [], [["Maintainable Code", "bold"], [": Enforces a structured approach to code organization and promotes cleaner, more readable code through interfaces and type annotations."]], [], [["Code Example:", "bold"]], [["function greet(name: string): void {", "sand"]], [["    console.log(`Hello, ${name}!`);", "sand"]], [["}", "sand"]], [], [["greet(\"World\");", "sand"]], [], [], [["⏱ 10.67s · ~9.6 tok/s · 102 tokens · ", "gray"], ["≈ $0.0024 saved", "green"], [" (session: $0.0024)", "gray"], [" (Dawn (Metal))"]]];
export const SUGGEST: Capture = [[["┌─", "dim"], [" "], ["Brimkern", "boldRed"], [" · "], ["Qwen 3 4B (BRIK int4)", "sand"], [" · "], ["Dawn (Metal)", "cyan"], [" · "], ["[CODE]", "cyan"], [" · think:"], ["auto", "cyan"]], [["kern ›", "boldRed"], [" /st"], ["atus", "dim"]], [["  /status         ", "cyan"], [" Session status"]], [["  /stats          ", "cyan"], [" Tokens, speed, estimated savings"]]];
export const PICKER: Capture = [[["┌─", "dim"], [" "], ["Brimkern", "boldRed"], [" · "], ["On-device model selector", "bold"], [" "], ["────────────────────────────────────────┐", "dim"]], [["  Use ↑/↓ to scroll · Enter to activate · Esc to cancel"]], [], [["    ┄", "dim"]], [["    "], ["coder      ", "cyan"], [" "], ["Qwen 3 4B                     ", "gray"], [" "], ["[", "dim"], ["BRIK int4 ", "sand"], ["]", "dim"], [" "], ["2.53 GB", "sand"], [" "], ["● active", "green bold"]], [["  "], ["❯", "boldRed"], [" "], ["fast       ", "cyan bold"], [" "], ["Qwen 2.5 Coder 1.5B           ", "bold"], [" "], ["[", "dim"], ["GGUF Q4_K_M", "sand"], ["]", "dim"], [" "], ["1.12 GB", "sand"]], [["    ┄", "dim"]], [], [["  "], ["┌─", "dim"], [" Spec sheet: Qwen 2.5 Coder 1.5B ", "sand"], ["────────────────────────────────────────────┐", "dim"]], [["  "], ["│", "dim"], [" "], ["Architecture:", "bold"], [" "], ["Qwen 2.5 Coder 1.5B", "sand"], ["  ·  "], ["Size:", "bold"], [" "], ["1.12 GB", "sand"], ["  ·  "], ["[Fast]", "cyan"], ["               "], ["│", "dim"]], [["  "], ["│", "dim"], [" "], ["Twice as fast (~25 tok/s) and lighter; review the code it suggests, it makes", "gray"], [" "], ["│", "dim"]], [["  "], ["│", "dim"], [" "], ["more mistakes.", "gray"], ["                                                               "], ["│", "dim"]], [["  "], ["│", "dim"], [" "], ["Format:", "bold"], [" "], ["GGUF Q4_K_M", "sand"], ["  ·  "], ["Engine:", "bold"], [" "], ["WebGPU (Chromium)", "green"], ["                            "], ["│", "dim"]], [["  "], ["│", "dim"], [" Command: /model fast                                                         "], ["│", "dim"]], [["  "], ["└──────────────────────────────────────────────────────────────────────────────┘", "dim"]]];
export const REPO: Capture = [[["kern ›", "boldRed"], [" what is this project for? answer in two sentences"]], [["This project aims to provide a local, GPU-accelerated AI model running environment without requiring an API key or server setup. It allows users to stream and run Hugging Face models directly in their browser using WebGPU and other technologies, with all processing done locally on the user's device."]], [], [["⏱ 8.45s · ~7.1 tok/s · 60 tokens · ", "gray"], ["≈ $0.0017 saved", "green"], [" (session: $0.0017)", "gray"], [" (Dawn (Metal))"]]];
export const STATUS: Capture = [[["┌─", "boldRed"], [" ", "sand"], ["Brimkern session status", "boldRed"], [" "], ["──────────────────────────────────────────────────┐", "boldRed"]], [["│", "boldRed"], [" "], ["Active model", "bold"], [" : "], ["Qwen 3 4B (BRIK int4)", "sand"], ["                                       "], ["│", "boldRed"]], [["│", "boldRed"], [" "], ["Engine & GPU", "bold"], [" : "], ["Native Dawn (in-process) · Dawn (Metal)", "cyan"], ["                     "], ["│", "boldRed"]], [["│", "boldRed"], [" "], ["AI mode     ", "bold"], [" : "], ["[CODE]", "cyan"], [" "], ["Direct code generation, exact syntax, concise", "gray"], ["        "], ["│", "boldRed"]], [["│", "boldRed"], [" "], ["Reasoning   ", "bold"], [" : "], ["auto", "cyan"], [" (Detects and formats <think>...</think> blocks)        "], ["│", "boldRed"]], [["│", "boldRed"], [" "], ["Git repo    ", "bold"], [" : "], ["main (modified *)", "sand"], ["                                           "], ["│", "boldRed"]], [["│", "boldRed"], [" "], ["Inference   ", "bold"], [" : "], ["100% local", "green"], [" · 60 tokens · ~7.1 tok/s (8.4s) · "], ["≈ $0.0017", "green"], ["      "], ["│", "boldRed"]], [["│", "boldRed"], ["                "], ["saved", "green"], ["                                                       "], ["│", "boldRed"]], [["└────────────────────────────────────────────────────────────────────────────┘", "boldRed"]]];
