import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  metadataBase: new URL("https://llm.romainkhanoyan.fr"),
  title: "Brimkern — Interface LLM Locale WebGPU",
  description: "Exécutez vos modèles de langage (LLM GGUF comme Qwen et Llama) localement dans votre navigateur. Accélération WebGPU, 100% confidentiel et hors-ligne.",
  keywords: ["LLM local", "WebGPU", "IA navigateur", "WGSL", "GGUF", "Qwen", "Llama 3", "Wllama", "IA privée"],
  authors: [{ name: "Romain Khanoyan" }],
  alternates: {
    canonical: "https://llm.romainkhanoyan.fr",
  },
  // og:image / twitter:image are generated by src/app/opengraph-image.tsx (1200×630).
  openGraph: {
    title: "Brimkern — Interface LLM Locale WebGPU",
    description: "Exécutez n'importe quel modèle LLM au format GGUF en local et accéléré par WebGPU directement dans votre navigateur.",
    url: "https://llm.romainkhanoyan.fr",
    siteName: "Brimkern",
    locale: "fr_FR",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "Brimkern — Interface LLM Locale WebGPU",
    description: "IA 100% locale dans le navigateur. Exécutez des GGUF de façon confidentielle avec accélération WebGPU.",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr" suppressHydrationWarning>
      <head>
        {/* Apply the saved theme before first paint so switching pages never flashes white in
            dark mode (runs synchronously during HTML parsing, ahead of React). type is
            text/javascript on the server (so it executes on hard load) and text/plain on the
            client (inert, and silences React's "script tag in a component" dev warning) — see
            next/docs preventing-flash-before-hydration. suppressHydrationWarning covers the type. */}
        <script
          type={typeof window === 'undefined' ? 'text/javascript' : 'text/plain'}
          suppressHydrationWarning
          dangerouslySetInnerHTML={{
            __html: `try{if(localStorage.getItem('brimkern-theme')==='dark')document.documentElement.classList.add('dark')}catch(e){}`,
          }}
        />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&family=Outfit:wght@400;500;600;700;800&family=Fira+Code:wght@400;500&display=swap" rel="stylesheet" />
      </head>
      <body>{children}</body>
    </html>
  );
}
