import type { Metadata } from "next";
import Script from "next/script";
import "./globals.css";
import { LocaleProvider } from "@/lib/i18n";

export const metadata: Metadata = {
  metadataBase: new URL("https://brimkern.romainkhanoyan.fr"),
  title: "Brimkern — Interface LLM Locale WebGPU",
  description: "Exécutez vos modèles de langage (LLM GGUF comme Qwen et Gemma) localement dans votre navigateur. Accélération WebGPU, 100% confidentiel et hors-ligne.",
  keywords: ["LLM local", "WebGPU", "IA navigateur", "WGSL", "GGUF", "Qwen", "Gemma", "IA privée", "IA hors-ligne"],
  authors: [{ name: "Romain Khanoyan" }],
  alternates: {
    canonical: "https://brimkern.romainkhanoyan.fr",
  },
  // og:image / twitter:image are generated by src/app/opengraph-image.tsx (1200×630).
  openGraph: {
    title: "Brimkern — Interface LLM Locale WebGPU",
    description: "Exécutez n'importe quel modèle LLM au format GGUF en local et accéléré par WebGPU directement dans votre navigateur.",
    url: "https://brimkern.romainkhanoyan.fr",
    siteName: "Brimkern",
    locale: "fr_FR",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "Brimkern — Interface LLM Locale WebGPU",
    description: "IA 100% locale dans le navigateur. Exécutez des GGUF de façon confidentielle avec accélération WebGPU.",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr" suppressHydrationWarning>
      <head>
        {/* Applique le thème sauvegardé avant le premier paint (pas de flash blanc en mode sombre à
            la navigation). next/script `beforeInteractive` = la voie App Router : injecté tôt dans le
            HTML initial, et exempt du warning React « script tag in a component » (contrairement à un
            <script> brut). Voir next/docs preventing-flash-before-hydration / scripts. */}
        <Script id="brimkern-theme-init" strategy="beforeInteractive" dangerouslySetInnerHTML={{
          __html: `try{if(localStorage.getItem('brimkern-theme')==='dark')document.documentElement.classList.add('dark')}catch(e){}`,
        }} />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        {/* Display : Fraunces (serif d'imprimerie, variable 400–900) — porte l'identité « Le Kern ». */}
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&family=Fraunces:opsz,wght@9..144,400..900&family=Fira+Code:wght@400;500&display=swap" rel="stylesheet" />
      </head>
      <body><LocaleProvider>{children}</LocaleProvider></body>
    </html>
  );
}
