import type { Metadata } from "next";
import Script from "next/script";
import { Suspense } from "react";
import PageViews from "./PageViews";
import { Inter, Fraunces, Fira_Code } from "next/font/google";
import { Analytics } from "@vercel/analytics/next";
import "./globals.css";
import { LocaleProvider } from "@/lib/i18n";
import { SITE_URL } from "@/lib/site";

// Polices SERVIES PAR NOUS. Elles venaient de fonts.googleapis.com / fonts.gstatic.com : mesuré en
// production, 153 Ko sur les 192 Ko de la page — 80 % du poids — et surtout une requête TIERCE, qui
// expose l'IP de chaque visiteur à Google. Sur une page dont l'argument central est « rien ne sort
// de votre navigateur, aucun serveur tiers », c'était l'incohérence la plus coûteuse du site.
// `next/font` télécharge les fichiers AU BUILD et les sert depuis notre domaine, avec un
// sous-ensemble de caractères et une métrique de repli calculée (donc pas de saut de mise en page).
// Chacune expose sa variable CSS ; globals.css les compose ensuite dans ses propres jetons
// (--font-sans / --font-heading / --font-mono), qui restent les seuls noms utilisés par le code.
const inter = Inter({ subsets: ["latin"], variable: "--font-inter", display: "swap" });
// `axes: ["opsz"]` : Fraunces est variable et son dessin CHANGE avec la taille optique — c'est ce
// que `.lp-h1 { font-optical-sizing: auto }` exploite pour le titre d'accueil. Sans cet axe, on
// perdrait le dessin « display » qui fait l'identité typographique.
const fraunces = Fraunces({ subsets: ["latin"], variable: "--font-fraunces", display: "swap", axes: ["opsz"] });
const firaCode = Fira_Code({ subsets: ["latin"], variable: "--font-fira", display: "swap" });

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: "Brimkern: Local WebGPU LLM engine in your browser",
  description: "Run any single-file GGUF from Hugging Face directly in your browser: WebGPU acceleration, hand-written WGSL kernels, no server, no API key, works offline.",
  // Les termes que notre public tape RÉELLEMENT — dont « web LLM » et « WebLLM alternative », la
  // requête par laquelle on cherche ce genre de moteur (cf. /vs-webllm, la comparaison mesurée).
  keywords: [
    "local LLM", "WebGPU", "browser AI", "WGSL", "GGUF", "in-browser inference", "on-device AI",
    "private AI", "offline AI", "LLM local", "IA navigateur",
    "web LLM", "WebLLM alternative", "run LLM in browser", "client-side LLM", "WebGPU inference",
    "browser LLM without server", "LLM dans le navigateur",
  ],
  authors: [{ name: "Romain Khanoyan", url: "https://romainkhanoyan.fr" }],
  creator: "Romain Khanoyan",
  publisher: "Romain Khanoyan",
  alternates: {
    canonical: SITE_URL,
    // hreflang : le signal officiel pour dire à un moteur « même page, autre langue ». Sans lui, deux
    // URLs bilingues se cannibalisent au lieu de se compléter. `x-default` désigne la version servie
    // quand aucune langue ne correspond.
    languages: {
      en: SITE_URL,
      fr: `${SITE_URL}/fr`,
      'x-default': SITE_URL,
    },
  },
  // og:image / twitter:image are generated by src/app/opengraph-image.tsx (1200×630).
  openGraph: {
    title: "Brimkern: Local WebGPU LLM engine in your browser",
    description: "Exécutez n'importe quel modèle LLM au format GGUF en local et accéléré par WebGPU directement dans votre navigateur.",
    url: SITE_URL,
    siteName: "Brimkern",
    locale: "en_US",
    // L'interface est bilingue SUR LA MÊME URL (bascule côté client) : on déclare l'anglais en
    // locale alternée plutôt que des hreflang, qui exigeraient des URL distinctes.
    alternateLocale: ["fr_FR"],
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "Brimkern: Local WebGPU LLM engine in your browser",
    description: "IA 100% locale dans le navigateur. Exécutez des GGUF de façon confidentielle avec accélération WebGPU.",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} ${fraunces.variable} ${firaCode.variable}`} suppressHydrationWarning>
      <head>
        {/* Applique le thème sauvegardé avant le premier paint (pas de flash blanc en mode sombre à
            la navigation). next/script `beforeInteractive` = la voie App Router : injecté tôt dans le
            HTML initial, et exempt du warning React « script tag in a component » (contrairement à un
            <script> brut). Voir next/docs preventing-flash-before-hydration / scripts. */}
        {/* Même pattern pour la sidebar : si elle était fermée, on la peint fermée dès le HTML
            statique (verrou CSS html.sb-closed, retiré à l'hydratation dans page.tsx) — sinon on
            la voit se refermer à chaque arrivée sur le site. */}
        <Script id="brimkern-theme-init" strategy="beforeInteractive" dangerouslySetInnerHTML={{
          __html: `try{if(localStorage.getItem('brimkern-theme')==='dark')document.documentElement.classList.add('dark');if(localStorage.getItem('brimkern-sidebar')==='0')document.documentElement.classList.add('sb-closed')}catch(e){}`,
        }} />
        {/* Les BRIK sont servis par huggingface.co (Range + redirection CDN) : payer le handshake
            TLS pendant que l'utilisateur lit l'accueil, pas à la première requête de 15 Mo. */}
        <link rel="preconnect" href="https://huggingface.co" crossOrigin="anonymous" />
      </head>
      <body>
        {/* Données structurées (schema.org) : décrit l'application ET son auteur. Deux effets :
            éligibilité aux résultats enrichis, et lien formel produit → personne (`sameAs`), qui
            renvoie une part de l'autorité du domaine vers romainkhanoyan.fr. JSON-LD plutôt que du
            microdata : aucune contrainte sur le balisage, et Google le recommande. */}
        <Script id="brimkern-jsonld" type="application/ld+json" strategy="afterInteractive" dangerouslySetInnerHTML={{
          __html: JSON.stringify({
            '@context': 'https://schema.org',
            '@graph': [
              {
                '@type': 'SoftwareApplication',
                '@id': `${SITE_URL}/#app`,
                name: 'Brimkern',
                url: SITE_URL,
                applicationCategory: 'DeveloperApplication',
                operatingSystem: 'Web (WebGPU)',
                description: "Moteur d'inférence LLM 100 % local dans le navigateur : GGUF et .brik exécutés sur le GPU du visiteur, sans serveur.",
                license: 'https://opensource.org/licenses/MIT',
                isAccessibleForFree: true,
                offers: { '@type': 'Offer', price: '0', priceCurrency: 'EUR' },
                author: { '@id': `${SITE_URL}/#author` },
                creator: { '@id': `${SITE_URL}/#author` },
              },
              {
                '@type': 'Person',
                '@id': `${SITE_URL}/#author`,
                name: 'Romain Khanoyan',
                url: 'https://romainkhanoyan.fr',
                sameAs: ['https://romainkhanoyan.fr'],
                jobTitle: 'Ingénieur logiciel : IA locale, WebGPU',
              },
            ],
          }),
        }} />
        <LocaleProvider initialLocale="en">{children}</LocaleProvider><Analytics />
        {/* Pages vues, envoyées par NOTRE code (aucun script tiers — cf. PageViews.tsx). Suspense
            parce que `useSearchParams` suspend le rendu statique : sans lui, tout l'arbre bascule en
            rendu dynamique et les 20 routes cessent d'être prérendues. */}
        <Suspense fallback={null}><PageViews /></Suspense>
      </body>
    </html>
  );
}
